site_name: Etendo Documentation

repo_url: https://github.com/etendosoftware
repo_name: etendosoftware
site_url: https://etendosoftware.github.io/docs.etendo.software/
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: In This Page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search:
      lang:
        - en
  - tags
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/etendosoftware
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/etendo-software/
      name: Linkedin

copyright: Copyright &copy; 2021 - 2023 Etendo Software

nav:
  - Home : index.md
  - Getting Started: 
    - Quickstart: getting-started/index.md
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - User interface:
      - Workspace: getting-started/user-interface/workspace.md
      - Navigation: getting-started/user-interface/navigation.md
      - Grid and Forms: getting-started/user-interface/grid-and-forms.md
  - Products:
    - Etendo ERP:
      - User Guide:
        - General Setup: products/etendo-erp/user-guide/general-setup/index.md
        - Jobs: products/etendo-erp/user-guide/jobs/index.md
        - Master Data Management: products/etendo-erp/user-guide/masterdata-management/index.md
        - Procurement Management: 
          - Transactions: products/etendo-erp/user-guide/procurement-management/transactions.md
          - Analysis Tools: products/etendo-erp/user-guide/procurement-management/analysis-tools.md
        - Warehouse Management: 
          - Transactions: products/etendo-erp/user-guide/warehouse-management/transactions.md
          - Analysis Tools: products/etendo-erp/user-guide/warehouse-management/analysis-tools.md
          - Setup: products/etendo-erp/user-guide/warehouse-management/setup.md
        - Production Management: 
          - Transactions:   products/etendo-erp/user-guide/production-management/transactions.md
          - Setup: products/etendo-erp/user-guide/production-management/setup.md
        - Etendo RX: products/etendo-erp/user-guide/etendo-rx/index.md
        - Material Requirement Planning: 
          - Transactions: products/etendo-erp/user-guide/material-requirement-planning/transactions.md
          - Setup: products/etendo-erp/user-guide/material-requirement-planning/setup.md
        - Sales Management: 
          - Transactions: products/etendo-erp/user-guide/sales-management/transactions.md
          - Analysis Tools: products/etendo-erp/user-guide/sales-management/analysis-tools.md
          - Setup: products/etendo-erp/user-guide/sales-management/setup.md 
        - Project & Service Management: products/etendo-erp/user-guide/project-and-services-management/index.md
        - Financial Management: 
          - Receivables and Payables:
            - Transactions: products/etendo-erp/user-guide/financial-management/receivables-and-payables/transactions.md
            - Analysis Tools: products/etendo-erp/user-guide/financial-management/receivables-and-payables/analysis-tools.md
            - Setup: products/etendo-erp/user-guide/financial-management/receivables-and-payables/setup.md
          - Accounting:
            - Transactions: products/etendo-erp/user-guide/financial-management/accounting/transactions.md
            - Analysis Tools: products/etendo-erp/user-guide/financial-management/accounting/analysis-tools.md
            - Setup: products/etendo-erp/user-guide/financial-management/accounting/setup.md
          - Assets: products/etendo-erp/user-guide/financial-management/assets/index.md
  - What's New:
    - Release Notes: whats-new/release-notes/index.md
    - Etendo Release Cycle: whats-new/etendo-release-cycle.md
    - Roadmap: whats-new/roadmap.md
  - Live Builds: live-builds/index.md
  - Help and Support: 
    - Support Service: help-and-support/index.md
    - Bug Report: help-and-support/how-to-report-bugs.md
  

