site_name: Etendo Documentation

repo_url: https://github.com/etendosoftware
repo_name: etendosoftware
site_url: https://docs.etendo.software
theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides/
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: In This Page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      separator: '[\s\.\-]+'
      lang:
        - en
  - tags
  - glightbox
  - rss:
      abstract_chars_count: 160  # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Europe/Paris
        default_time: "09:30"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/etendosoftware
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/etendo-software/
      name: Linkedin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/etendo.software/
      name: Instagram

copyright: Copyright &copy; 2021 - 2023 Etendo Software

nav:
  - Home : index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - User interface:
      - Workspace: getting-started/user-interface/workspace.md
      - Navigation: getting-started/user-interface/navigation.md
      - Grid and Forms: getting-started/user-interface/grid-and-forms.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Etendo Classic:
      - Basic Features:
        - General Setup: 
          - Overview: user-guide/etendo-classic/basic-features/general-setup/overview.md
          - Clear Report Cache: user-guide/etendo-classic/basic-features/general-setup/clear-report-cache.md
          - Attachments Configuration: user-guide/etendo-classic/basic-features/general-setup/attachments-configuration.md
          - Application: user-guide/etendo-classic/basic-features/general-setup/application.md
          - Client: user-guide/etendo-classic/basic-features/general-setup/client.md
          - CRM Connector: user-guide/etendo-classic/basic-features/general-setup/crm-connector.md
          - Enterprise Model: user-guide/etendo-classic/basic-features/general-setup/enterprise-model.md
          - Security: user-guide/etendo-classic/basic-features/general-setup/security.md
          - Process Scheduling: user-guide/etendo-classic/basic-features/general-setup/process-scheduling.md
        # - Jobs: user-guide/etendo-classic/basic-features/jobs/index.md
        - Master Data Management: 
          - Master Data: user-guide/etendo-classic/basic-features/master-data-management/master-data.md
          - Business Partner Setup: user-guide/etendo-classic/basic-features/master-data-management/business-partner-setup.md
          - Product Setup: user-guide/etendo-classic/basic-features/master-data-management/product-setup.md
          - Pricing: user-guide/etendo-classic/basic-features/master-data-management/pricing.md
        - Procurement Management:
          - Getting Started: user-guide/etendo-classic/basic-features/procurement-management/getting-started.md 
          - Transactions: user-guide/etendo-classic/basic-features/procurement-management/transactions.md
          - Analysis Tools: user-guide/etendo-classic/basic-features/procurement-management/analysis-tools.md
        - Warehouse Management:
          - Getting Started: user-guide/etendo-classic/basic-features/warehouse-management/getting-started.md 
          - Transactions: user-guide/etendo-classic/basic-features/warehouse-management/transactions.md
          - Analysis Tools: user-guide/etendo-classic/basic-features/warehouse-management/analysis-tools.md
          - Setup: user-guide/etendo-classic/basic-features/warehouse-management/setup.md
        - Production Management: 
          - Transactions:   user-guide/etendo-classic/basic-features/production-management/transactions.md
          - Setup: user-guide/etendo-classic/basic-features/production-management/setup.md
        - Material Requirement Planning: 
          - Transactions: user-guide/etendo-classic/basic-features/material-requirement-planning/transactions.md
          - Setup: user-guide/etendo-classic/basic-features/material-requirement-planning/setup.md
        - Sales Management: 
          - Getting Started: user-guide/etendo-classic/basic-features/sales-management/getting-started.md
          - Transactions: user-guide/etendo-classic/basic-features/sales-management/transactions.md
          - Analysis Tools: user-guide/etendo-classic/basic-features/sales-management/analysis-tools.md
          - Setup: user-guide/etendo-classic/basic-features/sales-management/setup.md 
        # - Project & Service Management: user-guide/etendo-classic/basic-features/project-and-services-management/index.md
        - Financial Management: 
          - Getting Started: user-guide/etendo-classic/basic-features/financial-management/getting-started.md
          - Receivables and Payables:
            - Transactions: user-guide/etendo-classic/basic-features/financial-management/receivables-and-payables/transactions.md
            - Analysis Tools: user-guide/etendo-classic/basic-features/financial-management/receivables-and-payables/analysis-tools.md
            - Setup: user-guide/etendo-classic/basic-features/financial-management/receivables-and-payables/setup.md
          - Accounting:
            - Transactions: user-guide/etendo-classic/basic-features/financial-management/accounting/transactions.md
            - Analysis Tools: user-guide/etendo-classic/basic-features/financial-management/accounting/analysis-tools.md
            - Setup: user-guide/etendo-classic/basic-features/financial-management/accounting/setup.md
          - Assets: user-guide/etendo-classic/basic-features/financial-management/assets/overview.md
      - Optional Features:
        - Bundles:
          - Essentials Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/essentials-extensions/overview.md
          - Platform Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/platform-extensions/overview.md
          - Warehouse Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/warehouse-extensions/overview.md
          - Production Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/production-extensions/overview.md
          - Sales Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/sales-extensions/overview.md
          - Financial Extensions Bundle: user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
          - Spanish Localization Bundle: user-guide/etendo-classic/optional-features/bundles/spain-localization/overview.md
          - Etendo BI Bundle: user-guide/etendo-classic/optional-features/bundles/etendobi-extensions/overview.md
        - Supported Modules:
          - Tax Report Launcher: user-guide/etendo-classic/optional-features/supported-modules/tax-report-launcher.md
      - How to Guides:
          - How to manage deferred revenue and expenses: user-guide/etendo-classic/how-to-guides/how-to-manage-deferred-revenue-and-expenses.md
          - How to manage prepaid invoices in payables: user-guide/etendo-classic/how-to-guides/how-to-manage-prepaid-invoices-in-payables.md
          - How to manage prepaid invoices in receivables: user-guide/etendo-classic/how-to-guides/how-to-manage-prepaid-invoices-in-receivables.md
          - How to transfer funds between financial accounts: user-guide/etendo-classic/how-to-guides/how-to-transfer-funds-between-financial-accounts.md
    - Etendo Mobile: 
      - Getting Started: user-guide/etendo-mobile/getting-started.md
      - User interface: user-guide/etendo-mobile/user-interface/user-interface.md
      - Bundles:
        - Etendo Classic Subapp Extensions: user-guide/etendo-mobile/bundles/etendo-classic-subapp-extensions/classic-subapp-extensions.md
    - Etendo Copilot: 
      - Getting Started:
        - Bastian: user-guide/etendo-copilot/getting-started/bastian.md

  - Developer Guide:
    - Overview: developer-guide/overview.md
    - Etendo Classic: 
      - Getting Started:
        - Installation :
          - Install Etendo Development Environment: developer-guide/etendo-classic/getting-started/installation/install-etendo-development-environment.md
          - IntelliJ Code Formatting: developer-guide/etendo-classic/getting-started/installation/intellij-code-formatting.md
          - Use of Repositories in Etendo: developer-guide/etendo-classic/getting-started/installation/use-of-repositories-in-etendo.md
          - Install Modules: developer-guide/etendo-classic/getting-started/installation/install-modules-in-etendo.md
          - Install Translation Bundles: developer-guide/etendo-classic/getting-started/installation/install-translation-bundles-in-etendo.md
        - Migration from Openbravo:
          - Migrating to Etendo (from Openbravo): developer-guide/etendo-classic/getting-started/migration-from-openbravo/migrating-to-etendo-from-openbravo.md
          - Upgrading to Openbravo 21Q3.2: developer-guide/etendo-classic/getting-started/migration-from-openbravo/upgrading-to-openbravo-21q3-2.md
        - Upgrade:
          - Upgrade Etendo to Any Version: developer-guide/etendo-classic/getting-started/upgrade/upgrade-etendo-to-any-version.md
          - Core format migration (JAR- Sources): developer-guide/etendo-classic/getting-started/upgrade/core-format-migration.md
          - Resolving Dependencies on GitHub: developer-guide/etendo-classic/getting-started/upgrade/resolving-dependencies-on-github.md
      - Concepts:
        - Etendo Jars: developer-guide/etendo-classic/concepts/etendo-jars.md
        - Inventory Status: developer-guide/etendo-classic/concepts/inventory-status.md
        - Naming Guideliness for Modules: developer-guide/etendo-classic/concepts/naming-guidelines-for-modules.md
      - How to guides: 
        - How to Publish Modules to a GitHub Repository: developer-guide/etendo-classic/how-to-guides/how-to-publish-modules-to-github-repository.md
        - How to Create and Update Translation Modules: developer-guide/etendo-classic/how-to-guides/how-to-create-and-update-translation-modules.md
        - How to Create Jobs and Actions: developer-guide/etendo-classic/how-to-guides/how-to-create-jobs-and-actions.md
        - How to Create a Clone Hook: developer-guide/etendo-classic/how-to-guides/how-to-create-a-clone-hook.md
        - How to Use Advanced Sequences: developer-guide/etendo-classic/how-to-guides/how-to-use-advanced-sequences.md
        - How to Create Scan Process: developer-guide/etendo-classic/how-to-guides/how-to-create-scan-process.md
        - How to Use Secure Webservices: developer-guide/etendo-classic/how-to-guides/how-to-use-secure-webservices.md
        - How to Copy and Paste Images in Etendo: developer-guide/etendo-classic/how-to-guides/how-to-copy-and-paste-images-in-etendo.md
        - How to Create a Module that Adds an Accounting Process: developer-guide/etendo-classic/how-to-guides/how-to-create-a-module-that-adds-an-accounting-process.md
        ### COPILOT_TOOL
      - Developer Tools:
        - Etendo Gradle Plugin: developer-guide/etendo-classic/developer-tools/etendo-gradle-plugin.md
        - Etendo Backup and Restore Plugin: developer-guide/etendo-classic/developer-tools/etendo-backup-restore-tool.md
      - Bundles:
        - Platform Extensions Bundle: developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
        - Warehouse Extensions Bundle: developer-guide/etendo-classic/bundles/warehouse-extensions-bundle.md
        - Financial Extensions Bundle: developer-guide/etendo-classic/bundles/financial-extensions-bundle.md
        - Etendo BI Bundle: developer-guide/etendo-classic/bundles/etendo-bi-bundle.md
    - Etendo RX:
      - Getting Started: developer-guide/etendo-rx/getting-started.md 
      - Concepts: 
        - Projections, Repository and Search: developer-guide/etendo-rx/concepts/projections.md
      - Tutorials:    
        - Creating a New Microservice: developer-guide/etendo-rx/tutorials/creating-a-new-microservice.md
      - How to guides:
        - How to Filter any request for Active or all Records:  developer-guide/etendo-rx/how-to-guides/how-to-filter-for-active-or-inactive.md
      #   - How to Format dates in a request:  developer-guide/etendo-rx/how-to-guides/how-to-change-date-format.md
      # - Developer Tools:
      #   - Etendo RX Plugin: developer-guide/etendo-rx/developer-tools/etendorx-plugin.md
      # - Integrations:
      #   - Etendo RX Authentication Keys: developer-guide/etendo-rx/integrations/setup-etendorx-authentication-keys.md
      #   - Zapier Integrations: developer-guide/etendo-rx/integrations/zapier-integrations.md
      #   - Zapier: developer-guide/etendo-rx/integrations/zapier.md
    - Etendo Copilot:
      - Overview: developer-guide/etendo-copilot/overview.md
      - Getting Started: developer-guide/etendo-copilot/installation.md
      - Available Tools:
        - XML Translation Tool: developer-guide/etendo-copilot/available-tools/xml-translation-tool.md
        - DB Query Tool: developer-guide/etendo-copilot/available-tools/db-query-tool.md
      - How to create Copilot tools: developer-guide/etendo-copilot/how-to-create-copilot-tools.md
    - Etendo Mobile:
      - Getting Started: developer-guide/etendo-mobile/getting-started.md 
      - Tutorials: 
        - Create New Subapplication: developer-guide/etendo-mobile/tutorials/create-new-subapplication.md
        - Example Subapplication Using Etendo RX: developer-guide/etendo-mobile/tutorials/example-subapplication-using-etendo-rx.md
      - Etendo UI Library: "https://develop--649b07373a33e896f7881dd9.chromatic.com/?path=/docs/how-to-install-steps--docs"
  - What's New:
    - Overview: whats-new/overview.md
    - Etendo Release Cycle: whats-new/etendo-release-cycle.md
    - Roadmap: "https://etendo.software"
    - Release Notes:
      - Etendo Classic:
        - Releases: whats-new/release-notes/etendo-classic/index.md
        - Etendo Gradle Plugin: whats-new/release-notes/etendo-classic/etendo-gradle-plugin.md
        - Bundles:
          - Essentials Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/essentials-extensions/release-notes.md
          - Platform Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/platform-extensions/release-notes.md
          - Warehouse Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/warehouse-extensions/release-notes.md
          - Production Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/production-extensions/release-notes.md
          - Sales Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/sales-extensions/release-notes.md
          - Financial Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/financial-extensions/release-notes.md
          - Spanish Localization Bundle: whats-new/release-notes/etendo-classic/bundles/spain-localization/release-notes.md
          - Etendo BI Bundle: whats-new/release-notes/etendo-classic/bundles/etendobi-extensions/release-notes.md
        - Translation Bundles:
          - Financial Extensions Bundle ES: whats-new/release-notes/etendo-classic/translation-bundles/financial-extensions-es/release-notes.md
        - Known Issues: whats-new/release-notes/etendo-classic/known-issues.md
      - Etendo Mobile:
        - Bundles:
          - Etendo Classic Subapp Extensions: whats-new/release-notes/etendo-mobile/bundles/classic-subapp-extensions/release-notes.md

  - Live Builds: live-builds/overview.md
  - Help and Support:
    - Overview: help-and-support/overview.md
    - Support Service: help-and-support/support-service.md
    - How to report bugs: help-and-support/how-to-report-bugs.md
