site_name: Etendo Documentation

repo_url: https://github.com/etendosoftware
repo_name: etendosoftware
site_url: https://etendosoftware.github.io/docs.etendo.software/
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
  - tags
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/etendosoftware
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/etendo-software/
      name: Linkedin

copyright: Copyright &copy; 2021 - 2023 Etendo Software

nav:
  - Home: 
    - Welcome: index.md
    - Requirements: requirements.md
    - Installation: installation.md
  - What's New:
    - Release Notes: whats-new/release-notes/index.md
    - Etendo Release Cycle: whats-new/etendo-release-cycle.md
    - Roadmap: whats-new/roadmap.md
  - Live Builds: live-builds/index.md
  - Help and Support: help-and-support/index.md
  

