site_name: Etendo Documentation

repo_url: https://github.com/etendosoftware
repo_name: etendosoftware
site_url: https://etendosoftware.github.io/docs/
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: In This Page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
  - tags
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/etendosoftware
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/etendo-software/
      name: Linkedin

copyright: Copyright &copy; 2021 - 2023 Etendo Software

nav:
  - Home : index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - User interface:
      - Workspace: getting-started/user-interface/workspace.md
      - Navigation: getting-started/user-interface/navigation.md
      - Grid and Forms: getting-started/user-interface/grid-and-forms.md
  - Products:
    - Overview: products/overview.md
    - Etendo Classic:
      - User Guide:
        - General Setup: 
          - Overview: products/etendo-classic/user-guide/general-setup/overview.md
          - Clear Report Cache: products/etendo-classic/user-guide/general-setup/clear-report-cache.md
          - Attachments Configuration: products/etendo-classic/user-guide/general-setup/attachments-configuration.md
          - Application: products/etendo-classic/user-guide/general-setup/application.md
          - Client: products/etendo-classic/user-guide/general-setup/client.md
          - CRM Connector: products/etendo-classic/user-guide/general-setup/crm-connector.md
          - Enterprise Model: products/etendo-classic/user-guide/general-setup/enterprise-model.md
          - Security: products/etendo-classic/user-guide/general-setup/security.md
          - Process Scheduling: products/etendo-classic/user-guide/general-setup/process-scheduling.md
        - Jobs: products/etendo-classic/user-guide/jobs/index.md
        - Master Data Management: 
          - Master Data: products/etendo-classic/user-guide/master-data-management/master-data.md
          - Business Partner Setup: products/etendo-classic/user-guide/master-data-management/business-partner-setup.md
          - Product Setup: products/etendo-classic/user-guide/master-data-management/product-setup.md
          - Pricing: products/etendo-classic/user-guide/master-data-management/pricing.md
        - Procurement Management: 
          - Transactions: products/etendo-classic/user-guide/procurement-management/transactions.md
          - Analysis Tools: products/etendo-classic/user-guide/procurement-management/analysis-tools.md
        - Warehouse Management: 
          - Transactions: products/etendo-classic/user-guide/warehouse-management/transactions.md
          - Analysis Tools: products/etendo-classic/user-guide/warehouse-management/analysis-tools.md
          - Setup: products/etendo-classic/user-guide/warehouse-management/setup.md
        - Production Management: 
          - Transactions:   products/etendo-classic/user-guide/production-management/transactions.md
          - Setup: products/etendo-classic/user-guide/production-management/setup.md
        - Etendo RX: products/etendo-classic/user-guide/etendo-rx/index.md
        - Material Requirement Planning: 
          - Transactions: products/etendo-classic/user-guide/material-requirement-planning/transactions.md
          - Setup: products/etendo-classic/user-guide/material-requirement-planning/setup.md
        - Sales Management: 
          - Transactions: products/etendo-classic/user-guide/sales-management/transactions.md
          - Analysis Tools: products/etendo-classic/user-guide/sales-management/analysis-tools.md
          - Setup: products/etendo-classic/user-guide/sales-management/setup.md 
        - Project & Service Management: products/etendo-classic/user-guide/project-and-services-management/index.md
        - Financial Management: 
          - Receivables and Payables:
            - Transactions: products/etendo-classic/user-guide/financial-management/receivables-and-payables/transactions.md
            - Analysis Tools: products/etendo-classic/user-guide/financial-management/receivables-and-payables/analysis-tools.md
            - Setup: products/etendo-classic/user-guide/financial-management/receivables-and-payables/setup.md
          - Accounting:
            - Transactions: products/etendo-classic/user-guide/financial-management/accounting/transactions.md
            - Analysis Tools: products/etendo-classic/user-guide/financial-management/accounting/analysis-tools.md
            - Setup: products/etendo-classic/user-guide/financial-management/accounting/setup.md
          - Assets: products/etendo-classic/user-guide/financial-management/assets/overview.md
      - Optional Features:
        - Bundles:
          - Essentials Extensions Bundle: 
            - Overview: products/etendo-classic/optional-features/bundles/essentials-extensions/overview.md
            - Advanced Business Partner: products/etendo-classic/optional-features/bundles/essentials-extensions/advanced-business-partner.md
          - Platform Extensions Bundle: 
            - Overview: products/etendo-classic/optional-features/bundles/platform-extensions/overview.md
            - Etendo Advanced Security: products/etendo-classic/optional-features/bundles/platform-extensions/etendo-advanced-security.md
          - Warehouse Extensions Bundle: products/etendo-classic/optional-features/bundles/warehouse-extensions/overview.md
          - Production Extensions Bundle: products/etendo-classic/optional-features/bundles/production-extensions/overview.md
          - Sales Extensions Bundle: products/etendo-classic/optional-features/bundles/sales-extensions/overview.md
          - Financial Extensions Bundle: 
            - Overview: products/etendo-classic/optional-features/bundles/financial-extensions/overview.md
            - Bulk Posting: products/etendo-classic/optional-features/bundles/financial-extensions/bulk-posting.md
            - Intercompany: products/etendo-classic/optional-features/bundles/financial-extensions/intercompany.md
          - Spanish Localization Bundle: 
            - Overview: products/etendo-classic/optional-features/bundles/spain-localization/overview.md
            - SII para IVA: products/etendo-classic/optional-features/bundles/spain-localization/sii-para-iva.md
            - Tax Report Modelo 303 (Spain): products/etendo-classic/optional-features/bundles/spain-localization/modelo-303.md
            - Withholding Report Modelo 190 (Spain): products/etendo-classic/optional-features/bundles/spain-localization/modelo-190.md
            - Spain AEAT Modelo 347 for APR: products/etendo-classic/optional-features/bundles/spain-localization/modelo-347.md
            - Modelo 349: products/etendo-classic/optional-features/bundles/spain-localization/modelo-349.md
            - Impuestos para España: products/etendo-classic/optional-features/bundles/spain-localization/impuestos-para-españa.md
            - Intrastat: products/etendo-classic/optional-features/bundles/spain-localization/intrastat.md
            - Tax Report Modelo 390 (Spain): products/etendo-classic/optional-features/bundles/spain-localization/modelo-390.md
            - Libro de Facturas: products/etendo-classic/optional-features/bundles/spain-localization/libro-de-facturas.md
            - Configuracion de Impuestos para Libro de Facturas: products/etendo-classic/optional-features/bundles/spain-localization/configuracion-de-impuestos-para-libro-de-facturas.md 
          - Etendo BI Bundle: 
            - Overview: products/etendo-classic/optional-features/bundles/etendobi-extensions/overview.md
            - Etendo BI Inclusion / Exclusion Module: products/etendo-classic/optional-features/bundles/etendobi-extensions/inclusion-exclusion-configuration.md
            - Etendo BI Connector Module: products/etendo-classic/optional-features/bundles/etendobi-extensions/etendo-bi-connector.md
        - Supported Modules:
          - Tax Report Launcher: products/etendo-classic/optional-features/supported-modules/tax-report-launcher.md
    - Etendo Mobile: 
      - Getting Started: products/etendo-mobile/getting-started.md
      - User interface: products/etendo-mobile/user-interface/user-interface.md
    - Etendo Copilot: 
      - Getting Started:
        - Bastian: products/etendo-copilot/getting-started/bastian.md
  - What's New:
    - Overview: whats-new/overview.md
    - Etendo Release Cycle: whats-new/etendo-release-cycle.md
    - Roadmap: "https://www.etendo.software"
    - Release Notes:
      - Etendo Classic:
        - Releases: whats-new/release-notes/etendo-classic/index.md
        - Etendo Gradle Plugin: whats-new/release-notes/etendo-classic/etendo-gradle-plugin.md
        - Bundles:
          - Essentials Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/essentials-extensions/release-notes.md
          - Platform Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/platform-extensions/release-notes.md
          - Warehouse Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/warehouse-extensions/release-notes.md
          - Production Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/production-extensions/release-notes.md
          - Sales Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/sales-extensions/release-notes.md
          - Financial Extensions Bundle: whats-new/release-notes/etendo-classic/bundles/financial-extensions/release-notes.md
          - Spanish Localization Bundle: whats-new/release-notes/etendo-classic/bundles/spain-localization/release-notes.md
          - Etendo BI Bundle: whats-new/release-notes/etendo-classic/bundles/etendobi-extensions/release-notes.md
        - Known Issues: whats-new/release-notes/etendo-classic/known-issues.md

  - Developer Guide:
    - Overview: developer-guide/overview.md
    - Etendo Classic: 
      - Getting Started:
        - Installation :
          - Install Etendo Development Environment: developer-guide/etendo-classic/getting-started/installation/install-etendo-development-environment.md
          - IntelliJ Code Formatting: developer-guide/etendo-classic/getting-started/installation/intellij-code-formatting.md
          - Use of Repositories in Etendo: developer-guide/etendo-classic/getting-started/installation/use-of-repositories-in-etendo.md
          - Install Modules from Marketplace: developer-guide/etendo-classic/getting-started/installation/install-modules-from-marketplace.md
        - Migration from Openbravo:
          - Migrating to Etendo (from Openbravo): developer-guide/etendo-classic/getting-started/migration-from-openbravo/migrating-to-etendo-from-openbravo.md
          - Upgrading to Openbravo 21Q3.2: developer-guide/etendo-classic/getting-started/migration-from-openbravo/upgrading-to-openbravo-21q3-2.md
        - Upgrade:
          - Upgrade Etendo to Any Version: developer-guide/etendo-classic/getting-started/upgrade/upgrade-etendo-to-any-version.md
          - Core format migration (JAR- Sources): developer-guide/etendo-classic/getting-started/upgrade/core-format-migration.md
          - Resolving Dependencies on GitHub: developer-guide/etendo-classic/getting-started/upgrade/resolving-dependencies-on-github.md
      - Concepts:
        - Etendo Jars: developer-guide/etendo-classic/concepts/etendo-jars.md
        - Inventory Status: developer-guide/etendo-classic/concepts/inventory-status.md
      - How to guides: 
        - How to Publish Modules to a GitHub Repository: developer-guide/etendo-classic/how-to-guides/how-to-publish-modules-to-github-repository.md
        - How to Create and Update Translation Modules: developer-guide/etendo-classic/how-to-guides/how-to-create-and-update-translation-modules.md
        - How to Create Jobs and Actions: developer-guide/etendo-classic/how-to-guides/how-to-create-jobs-and-actions.md
        - How to Create a Clone Hook: developer-guide/etendo-classic/how-to-guides/how-to-create-a-clone-hook.md
        - How to Use Advanced Sequences: developer-guide/etendo-classic/how-to-guides/how-to-use-advanced-sequences.md
        - How to Create Scan Process: developer-guide/etendo-classic/how-to-guides/how-to-create-scan-process.md
        - How to Use Secure Webservices: developer-guide/etendo-classic/how-to-guides/how-to-use-secure-webservices.md
        - How to Copy and Paste Images in Etendo: developer-guide/etendo-classic/how-to-guides/how-to-copy-and-paste-images-in-etendo.md
      - Developer Tools:
        - Etendo Gradle Plugin: developer-guide/etendo-classic/developer-tools/etendo-gradle-plugin.md
        - Etendo Backup and Restore Plugin: developer-guide/etendo-classic/developer-tools/etendo-backup-restore-tool.md
      - Bundles:
        - Platform Extensions Bundle: developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
        - Warehouse Extensions Bundle: developer-guide/etendo-classic/bundles/warehouse-extensions-bundle.md
        - Financial Extensions Bundle: developer-guide/etendo-classic/bundles/financial-extensions-bundle.md
        - Spanish Localization Bundle: developer-guide/etendo-classic/bundles/spanish-localization-bundle.md
        - Etendo BI Bundle: developer-guide/etendo-classic/bundles/etendo-bi-bundle.md
    - Etendo RX:
      - Tutorial:   
        - Getting Started:
          - Installation: developer-guide/etendo-rx/tutorials/installation.md 
        - First Steps: developer-guide/etendo-rx/tutorials/first-steps.md
      - How to guides:
        - How to Filter any request for Active or all Records:  developer-guide/etendo-rx/how-to-guides/how-to-filter-for-active-or-inactive.md
        - How to Format dates in a request:  developer-guide/etendo-rx/how-to-guides/how-to-change-date-format.md
      - Tutorial:   
        - First Steps: developer-guide/etendo-rx/tutorials/first-steps.md
    - Etendo Copilot:
      - Overview: developer-guide/etendo-copilot/overview.md
      - Getting Started: developer-guide/etendo-copilot/getting-started.md 
  - Live Builds: live-builds/overview.md
  - Help and Support:
    - Overview: help-and-support/overview.md
    - Support Service: help-and-support/support-service.md
    - How to report bugs: help-and-support/how-to-report-bugs.md
